# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f31034ccb6bafd7d03689dfac1bdfc94dfb4d911fcd3b135f2e1c8e44239f992e7b7da499f2d404525646f7e70c20f64e5bef4be02b90234fce1acca272d30f

test:
  secret_key_base: bfaa23a0e859539fe54383946df955c7243e42b98e2ec3ca3617af672f355becc4b309d052f926497d3a57509da35136f566838f721617dedd5a18d6ba1fde28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
